version: '3'
services:

  ##### NGINX #####
  rl-frontend:

    ports:
      - "80:80"

    tty: true
    restart: always
    container_name: rl-frontend
    hostname: rl-frontend

    depends_on:
        - rl-backend

    build:
      context: ./frontend-context/

    networks:
      rl-network:
        ipv4_address: 192.168.200.2

    entrypoint: ["/init-frontend.sh"]

    command: ["nginx", "-g", "daemon off;"]

  ##### Flask #####
  rl-backend:

    networks:
      rl-network:
        ipv4_address: 192.168.200.3

    restart: always
    container_name: rl-backend
    hostname: rl-backend

    depends_on:
        - rl-database

    build:
      context: ./backend-context/
      args:
        - flask_port=5000

    ports:
        - 5000:5000

    environment:
        - FLASK_APP='app'
        - FLASK_PORT=5000
        - DB_USER=rl-user
        - IN_CONTAINER=True
        - DB_PASSWORD=rl-specialpassword
        - DB_SERVER=rl-database
        - DB_NAME=rl-database
        - LC_ALL=C.UTF-8
        - LANG=C.UTF-8

  ##### MySQL #####
  rl-database:

    image: mysql
    restart: always
    privileged: true

    networks:
      rl-network:
        ipv4_address: 192.168.200.4

    environment:
        - MYSQL_DATABASE=rl-database
        - MYSQL_USER=rl-user
        - MYSQL_PASSWORD=rl-specialpassword
        - MYSQL_ROOT_PASSWORD=root
        - TZ=Europe/Bucharest

    ports:
        - 3306:3306

    volumes:
        - /var/rl-app/db-volume:/var/lib/mysql

    container_name: rl-database
    hostname: rl-database


### Networks ###
networks:
  rl-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
