version: '3'
services:

  ##### NGINX #####
  rl-frontend:
    image: rlrules/docker-lab-frontend
    depends_on:
      - rl-backend
    restart: always
    ports:
      - 80:80
    networks:
      - rl-network
    environment:
      - FRONTEND_NODE=one
      - BACKEND_SERVER=rl-backend

  ##### Flask #####
  rl-backend:
    image: rlrules/docker-lab-backend
    depends_on:
      - rl-database
    restart: always

    networks:
      - rl-network
    #volumes:
    #   - /var/rl-app/rl-images:/home/rl-user/rl-app/rl-images/

    environment:
      - FLASK_APP=run.py
      - FLASK_PORT=5000
      - DB_USER=rl-user
      - IN_CONTAINER=True
      - DB_PASSWORD=rl-specialpassword
      - DB_SERVER=rl-database
      - DB_NAME=rl-database
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

  ##### MySQL #####
  rl-database:
    image: rlrules/docker-lab-database
    restart: always

    container_name: rl-database
    hostname: rl-database

    networks:
      - rl-network
    #volumes:
    #   - /var/rl-app/db-volume:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=rl-database
      - MYSQL_USER=rl-user
      - MYSQL_PASSWORD=rl-specialpassword
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Bucharest

### Networks ###
networks:
  rl-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24

