"""empty message

Revision ID: fa00b9e0d963
Revises: faa907d32929
Create Date: 2019-12-02 12:18:11.365892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa00b9e0d963'
down_revision = 'faa907d32929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('likes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'likes_count')
    # ### end Alembic commands ###
